
export type RibbonTabId =
  | "home"
  | "insert"
  | "table"
  | "view"
  | "export"
  | "settings"
  | "help";

export type RibbonGroupId =
  | "history"
  | "paragraph"
  | "textFormat"
  | "clear"
  | "basic"
  | "block"
  | "assist"
  | "rows"
  | "columns"
  | "alignment"
  | "excel"
  | "pane"
  | "preview"
  | "theme"
  | "pdf"
  | "html"
  | "inspection"
  | "images"
  | "help";

export type RibbonItemId =
  | "undo"
  | "redo"
  | "style"
  | "quote"
  | "bulletList"
  | "orderedList"
  | "taskList"
  | "indent"
  | "outdent"
  | "bold"
  | "italic"
  | "strike"
  | "underline"
  | "highlight"
  | "code"
  | "superscript"
  | "subscript"
  | "textColor"
  | "clearInline"
  | "clearBlock"
  | "link"
  | "image"
  | "tableSize"
  | "insertTable"
  | "horizontalRule"
  | "hardBreak"
  | "codeLanguage"
  | "codeBlock"
  | "mermaid"
  | "math"
  | "footnote"
  | "toc"
  | "pageBreak"
  | "note"
  | "warning"
  | "emoji"
  | "insertEmoji"
  | "rowBefore"
  | "rowAfter"
  | "deleteRow"
  | "colBefore"
  | "colAfter"
  | "deleteColumn"
  | "tableHeader"
  | "alignLeft"
  | "alignCenter"
  | "alignRight"
  | "alignColumns"
  | "cellBreak"
  | "openTableEditor"
  | "copyTsv"
  | "openSource"
  | "outline"
  | "scrollSync"
  | "zoomHint"
  | "imageResize"
  | "editorTheme"
  | "openPrintSettings"
  | "printPreview"
  | "exportPdf"
  | "embedImages"
  | "convertLinkedMarkdown"
  | "saveWithoutDialog"
  | "exportHtml"
  | "preflight"
  | "imageDirectory"
  | "shortcuts"
  | "features";

export type RibbonHeaderButtonId =
  | "search"
  | "splitView"
  | "textOnly"
  | "previewOnly";

export type RibbonHeaderItemId = RibbonHeaderButtonId | "collapse";

export type RibbonContainerId = "tableInsertForm";

export type RibbonHeaderGroupId = "viewModes";
